### ISSUE TITLE
3 tests fail

### ISSUE THREAD

**Issue by idoan** [JElbourne/aliasnerd#1]
You need to change 3 "test.host" strings in your SubscriptionControllerTest to "localhost" , otherwise 3 tests fail.

**Comment by JElbourne** [comment]
Ya I have not looked at those failing tests to hard yet. I know its a path problem with the localhost.

I plan and getting those 3 tests passing soon, still contemplating the way I wrote that code, maybe change the implementation maybe not.

**Comment by idoan** [comment]
thanks for reply,  might have missed it but what difference does it make whether you use localhost or test.host for testing ?

and what other features do you plan to add to this app?

do you also plan to show how to deploy this to digital ocean or other hosting providers in contrast to heroku, which is just SAAS ?

**Comment by JElbourne** [comment]
I made the suggested change to the SubscriptionControllerTest, thanks @idoan.
All tests pass and have 100% coverage at this time.
